[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_contracts = "69LrDhtKu2M6FXuF1mqJCM9s2J427XV19QFg972MWg9A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/degencodebeast/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
